[package]
name = "bricklayer"
version = "0.1.0"
edition = "2021"
description = "An IDP(internal developer platform)"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
